community/icu/build
=> icu: disable ccache to fix clang issue

.github/PULL_REQUEST_TEMPLATE.md, README
replace k1ss.org links with kiss.armaanb.net, and replace @dylanaraps with @git-bruh
=> meta: update PR template and readme

community/refind/build
=> refind: fixed install

update
Adds link to BDFL poll in update file
=> meta: add poll notice to update file

community/mosh/build
Read: https://kiss.armaanb.net/wiki/kiss/style-guide
---
```
MANIFEST HERE
```
=> mosh: update build

community/lariza/depends
=> lariza: fix depends

community/webkit2gtk/build, community/webkit2gtk/depends
Closes #385
```
/var/db/kiss/installed/webkit2gtk/version
/var/db/kiss/installed/webkit2gtk/sources
/var/db/kiss/installed/webkit2gtk/manifest
/var/db/kiss/installed/webkit2gtk/depends
/var/db/kiss/installed/webkit2gtk/checksums
/var/db/kiss/installed/webkit2gtk/build
/var/db/kiss/installed/webkit2gtk/
/var/db/kiss/
/var/db/
/var/
/usr/lib/webkit2gtk-4.0/jsc
/usr/lib/webkit2gtk-4.0/injected-bundle/libwebkit2gtkinjectedbundle.so
/usr/lib/webkit2gtk-4.0/injected-bundle/
/usr/lib/webkit2gtk-4.0/WebKitWebProcess
/usr/lib/webkit2gtk-4.0/WebKitNetworkProcess
/usr/lib/webkit2gtk-4.0/
/usr/lib/pkgconfig/webkit2gtk-web-extension-4.0.pc
/usr/lib/pkgconfig/webkit2gtk-4.0.pc
/usr/lib/pkgconfig/javascriptcoregtk-4.0.pc
/usr/lib/pkgconfig/ …
```
=> webkit2gtk: make gst stuff optional again

community/gst-plugins-base/build, community/gst-plugins/build
gst-plugins: https://termbin.com/5rdd, gst-plugins-base: https://termbin.com/bp4n
=> gst-plugins*: Disable tests and introspection

community/gst-plugins/depends
/var/db/kiss/installed/gst-plugins/version
/var/db/kiss/installed/gst-plugins/sources
/var/db/kiss/installed/gst-plugins/manifest
/var/db/kiss/installed/gst-plugins/depends
/var/db/kiss/installed/gst-plugins/checksums
/var/db/kiss/installed/gst-plugins/build
/var/db/kiss/installed/gst-plugins/
/var/db/kiss/
/var/db/
/var/
/usr/share/gstreamer-1.0/presets/GstX264Enc.prs
/usr/share/gstreamer-1.0/presets/GstVP8Enc.prs
/usr/share/gstreamer-1.0/presets/GstQTMux.prs
/usr/share/gstreamer-1.0/presets/GstIirEqualizer3Bands.prs
/usr/share/gstreamer-1.0/presets/GstIirEqualizer10Bands.prs
/usr/share/gstreamer-1.0/presets/GstFreeverb.prs
/usr/share/gstreamer-1.0/presets/
/usr/share/gstreamer-1.0/encoding-profiles/online-services/youtube.gep …
=> gst-plugins: remove X and libressl

community/megatools/depends
- [Y] I am the maintainer of this package.
=> megatools: update depends

community/openntpd/depends
=> openntpd: depend on openssl

community/irssi/depends
=> irssi: depend on openssl

community/bemenu/depends
https://github.com/kiss-community/community/issues/635
=> bemenu: fix depends

community/qbe/build
KISS exporting DESTDIR made the package install to KISS_TMPDIR
=> qbe: fix DESTDIR

community/tty-clock/build
=> fix build script for DESTDIR changes

community/ioping/build
=> ioping: fix build script

.github/workflows/lint.yml
=> run kiss-lint on pull requests

community/yt-dlp/depends, community/yt-dlp/files/youtube-dl
=> yt-dlp: fix

community/json-glib/build
fixing error
```
/var/db/kiss/installed/json-glib/version
/var/db/kiss/installed/json-glib/sources
/var/db/kiss/installed/json-glib/manifest
/var/db/kiss/installed/json-glib/depends
/var/db/kiss/installed/json-glib/checksums
/var/db/kiss/installed/json-glib/build
/var/db/kiss/installed/json-glib/
/var/db/kiss/
/var/db/
/var/
/usr/share/installed-tests/json-glib-1.0/serialize-simple.test
/usr/share/installed-tests/json-glib-1.0/serialize-full.test
/usr/share/installed-tests/json-glib-1.0/serialize-complex.test
/usr/share/installed-tests/json-glib-1.0/reader.test
/usr/share/installed-tests/json-glib-1.0/path.test
/usr/share/installed-tests/json-glib-1.0/parser.test
/usr/share/installed-tests/json-glib-1.0/object.test
/usr/share/installed-tests/json-glib-1.0/node.test …
```
=> json-glib: fix error

community/swayidle/depends
Read: https://k1sslinux.org/wiki/kiss/style-guide
Please include the manifest for version bumps and new packages.
---
idle action utility for wayland compositors
```
<no change>
```
=> swayidle: add missing depends

community/swaylock/depends
Read: https://k1sslinux.org/wiki/kiss/style-guide
Please include the manifest for version bumps and new packages.
---
screenlocking utility for wayland compositors
```
<no change>
```
=> swaylock: add missing depends

community/rsync/build, community/rsync/depends
=> rsync: explicit DESTDIR, no static link

community/kmod/build, community/kmod/depends
Read: https://k1sslinux.org/wiki/kiss/style-guide
Please include the manifest for version bumps and new packages.
---
```
MANIFEST HERE
```
=> kmod: add zstd support, closes #1003

community/sdl2/build
Read: https://k1sslinux.org/wiki/kiss/style-guide
Please include the manifest for version bumps and new packages.
---
```
/var/db/kiss/installed/sdl2/version
/var/db/kiss/installed/sdl2/sources
/var/db/kiss/installed/sdl2/post-install
/var/db/kiss/installed/sdl2/manifest
/var/db/kiss/installed/sdl2/depends
/var/db/kiss/installed/sdl2/checksums
/var/db/kiss/installed/sdl2/build
/var/db/kiss/installed/sdl2/
/var/db/kiss/
/var/db/
/var/
/usr/share/aclocal/sdl2.m4
/usr/share/aclocal/
/usr/share/
/usr/lib64/pkgconfig/sdl2.pc
/usr/lib64/pkgconfig/
/usr/lib64/libSDL2main.a
/usr/lib64/libSDL2.so
/usr/lib64/libSDL2.a
/usr/lib64/libSDL2-2.0.so.0.22.0
/usr/lib64/libSDL2-2.0.so.0
/usr/lib64/libSDL2-2.0.so …
```
=> sdl2: adopt and fix build for wayland

community/oksh/build
```
/var/db/kiss/installed/oksh/version
/var/db/kiss/installed/oksh/sources
/var/db/kiss/installed/oksh/manifest
/var/db/kiss/installed/oksh/checksums
/var/db/kiss/installed/oksh/build
/var/db/kiss/installed/oksh/
/var/db/kiss/
/var/db/
/var/
/usr/share/man/man1/ksh.1
/usr/share/man/man1/
/usr/share/man/
/usr/share/
/usr/bin/ksh
/usr/bin/
/usr/
```
=> oksh: remove -DSMALL

community/json-glib/depends
=> json-glib: remove python dependencie
